title: LucaStory
avatar: profile2
bg_img: bg1
baseurl: 
markdown: kramdown
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/blog/page:num/"
disqus_shortname: lucaslionline
excerpt_separator: '<!-- more -->'
